services:
  mysql:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_USER
      MYSQL_DATABASE: $MYSQLDB_DATABASE

  # app:
  #   depends_on: [mysql]
  #   image: node:18-alpine
  #   command: sh -c "npm install && npx prisma generate && npm run migrate &&  npm run seed"
  #   ports:
  #     - 127.0.0.1:8080:8080
  #   working_dir: /app
  #   env_file: ./.env
  #   volumes:
  #     - ./:/app
  #   environment:
  #     DATABASE_URL: mysql://$MYSQLDB_USER:$MYSQLDB_ROOT_PASSWORD@db:$MYSQLDB_LOCAL_PORT/$MYSQLDB_DATABASE

volumes:
  mysql:
